// Generated by CoffeeScript 1.7.1
var Button, Dialog, LoadedProject, choosePort;

Button = Remix.create({
  template: '<button type="button" class="btn"></button>',
  remixEvent: {
    'click': 'clickCallback'
  },
  render: function(data) {
    this.node.attr('class', "btn btn-" + data.type + " btn-" + data.size);
    this.node.text(data.title);
    return this.clickCallback = data.onclick;
  }
});

LoadedProject = Remix.create({
  remixChild: {
    Button: Button
  },
  template: "<div class=\"col-sm-6 col-md-4\" style=\"display: none\">\n	<div class=\"panel panel-primary\">\n		<div class=\"panel-heading\">\n			<button remix=\"Button\" data-type=\"danger\" data-size=\"xs\" data-onclick=\"@unloadProject\" data-title=\"X\" key=\"unloadBtn\"></button> &nbsp;&nbsp;<span ref=\"pathtxt\"></span>\n		</div>\n		<div class=\"panel-body\">\n			<ul ref=\"urlList\">\n				\n			</ul>\n		</div>\n		<div class=\"panel-footer\">\n			<p class=\"text-right\">\n	  			<button remix=\"Button\" data-type=\"primary\" data-size=\"xs\" data-onclick=\"@configProject\" data-title=\"配置\" key=\"configBtn\"></button>\n	  			<button remix=\"Button\" data-type=\"info\" data-size=\"xs\" data-onclick=\"@openDirectory\" data-title=\"打开目录\" key=\"openDirBtn\"></button>\n	  			<button remix=\"Button\" data-type=\"danger\" data-size=\"xs\" data-onclick=\"@packProject\" data-title=\"打包\" key=\"packBtn\"></button>\n		  	</p>\n		</div>\n	</div>\n</div>",
  onNodeCreated: function() {
    return this.appendTo('#loaded-container');
  },
  render: function(data) {
    this.pathtxt.text(data.path);
    this.urlList.empty();
    data.urls.forEach((function(_this) {
      return function(url) {
        return _this.urlList.append("<li><a href=\"" + url + "\">" + url + "</a></li>");
      };
    })(this));
    this.openDirectory = data.openDirectory, this.unloadProject = data.unloadProject, this.configProject = data.configProject, this.packProject = data.packProject;
    return this.node.slideDown('fast');
  },
  slideDestroy: function() {
    return this.node.slideUp('fast', (function(_this) {
      return function() {
        return _this.destroy();
      };
    })(this));
  }
});

Dialog = Remix.create({
  template: "<div class=\"modal\">\n	<div class=\"modal-backdrop fade in\"></div>\n  <div class=\"modal-dialog\">\n    <div class=\"modal-content\">\n      <div class=\"modal-header\">\n        <button type=\"button\" class=\"close\" aria-label=\"Close\"><span aria-hidden=\"true\">&times;</span></button>\n        <h4 class=\"modal-title\" ref=\"title\">Modal title</h4>\n      </div>\n      <div class=\"modal-body\" ref=\"body\">\n        <p>Loading...</p>\n      </div>\n      <div class=\"modal-footer\" ref=\"footer\">\n      	\n      </div>\n    </div><!-- /.modal-content -->\n  </div><!-- /.modal-dialog -->\n</div>",
  remixEvent: {
    'click, .close': 'slideAway'
  },
  onNodeCreated: function() {
    return this.appendTo(document.body);
  },
  render: function(data) {
    this.title.text(data.title);
    this.body.empty().append(data.content);
    this.footer.empty().append(data.buttons);
    return this.node.slideDown();
  },
  slideAway: function() {
    return this.node.slideUp(300, (function(_this) {
      return function() {
        return _this.destroy();
      };
    })(this));
  }
});

choosePort = function(callback) {
  return Dialog({
    title: '80端口已被占用，请输入你想要的端口号',
    content: Remix.create({
      template: "<div class=\"input-group\">\n	<input type=\"file\" class=\"form-control\" nwdirectory>\n	<div class=\"input-group-btn\">\n		<button type=\"button\" class=\"btn btn-success\" tabindex=\"-1\">载入</button>\n	</div>\n</div>"
    }),
    buttons: Remix.create({
      remixChild: {
        Button: Button
      },
      template: "<p><button remix=\"Button\" data-type=\"primary\" data-size=\"xs\" data-onclick=\"@configProject\" data-title=\"确定\" key=\"configBtn\"></button></p>"
    })
  });
};

choosePort();
